// Shared converters data used across the application
export interface ConverterData {
  id: string
  name: string
  category: string
  baseUnit: string
  tags: string[]
  keywords: string[]
  units?: number // For display purposes
  isNew?: boolean // For homepage badges
}

export const convertersData: ConverterData[] = [
  {
    id: "mass",
    name: "Mass Converter",
    category: "mass",
    baseUnit: "gram",
    tags: ["mg", "g", "kg", "lb", "oz", "ton"],
    keywords: ["weight", "mass", "kilogram", "pound", "gram", "ounce", "metric", "imperial"],
    units: 7,
    isNew: true,
  },
  {
    id: "length",
    name: "Length Converter",
    category: "length",
    baseUnit: "meter",
    tags: ["mm", "cm", "m", "km", "in", "ft", "mi"],
    keywords: ["distance", "length", "height", "width", "meter", "foot", "inch", "mile", "kilometer"],
    units: 9,
  },
  {
    id: "area",
    name: "Area Converter",
    category: "area",
    baseUnit: "square meter",
    tags: ["m²", "km²", "acre", "ft²", "ha"],
    keywords: ["area", "surface", "square", "acre", "hectare", "land", "property"],
    units: 7,
    isNew: true,
  },
  {
    id: "volume",
    name: "Volume Converter",
    category: "volume",
    baseUnit: "liter",
    tags: ["ml", "L", "gal", "m³", "cup", "qt"],
    keywords: ["volume", "capacity", "liquid", "fluid", "liter", "gallon", "cup", "quart"],
    units: 8,
  },
  {
    id: "temperature",
    name: "Temperature Converter",
    category: "temperature",
    baseUnit: "celsius",
    tags: ["°C", "°F", "K", "°R"],
    keywords: ["temperature", "heat", "cold", "celsius", "fahrenheit", "kelvin", "rankine", "weather"],
    units: 5,
    isNew: true,
  },
  {
    id: "time",
    name: "Time Converter",
    category: "time",
    baseUnit: "second",
    tags: ["ms", "s", "min", "hr", "day", "week", "year"],
    keywords: ["time", "duration", "period", "second", "minute", "hour", "day", "week", "month", "year"],
    units: 9,
  },
  {
    id: "digital",
    name: "Digital Converter",
    category: "digital",
    baseUnit: "byte",
    tags: ["KB", "MB", "GB", "TB", "bit", "byte"],
    keywords: ["digital", "storage", "memory", "data", "file", "size", "computer", "byte", "bit"],
    units: 6,
  },
  {
    id: "speed",
    name: "Speed Converter",
    category: "speed",
    baseUnit: "meter per second",
    tags: ["m/s", "km/h", "mph", "knot"],
    keywords: ["speed", "velocity", "fast", "slow", "car", "vehicle", "wind", "travel"],
    units: 5,
  },
  {
    id: "pressure",
    name: "Pressure Converter",
    category: "pressure",
    baseUnit: "pascal",
    tags: ["Pa", "kPa", "bar", "psi", "atm"],
    keywords: ["pressure", "force", "atmospheric", "tire", "weather", "pascal", "bar"],
    units: 5,
  },
  {
    id: "energy",
    name: "Energy Converter",
    category: "energy",
    baseUnit: "joule",
    tags: ["J", "kJ", "cal", "kWh", "Wh"],
    keywords: ["energy", "power", "electricity", "calorie", "joule", "watt", "battery"],
    units: 6,
  },
  {
    id: "power",
    name: "Power Converter",
    category: "power",
    baseUnit: "watt",
    tags: ["W", "kW", "MW", "hp", "BTU/h"],
    keywords: ["power", "electricity", "watt", "horsepower", "engine", "motor", "electrical"],
    units: 7,
  },
  {
    id: "parts-per",
    name: "Parts Per Converter",
    category: "other",
    baseUnit: "parts per million",
    tags: ["ppm", "ppb", "ppt", "%", "‰"],
    keywords: ["concentration", "ratio", "percentage", "parts", "million", "billion", "pollution"],
    units: 5,
  },
  {
    id: "pace",
    name: "Pace Converter",
    category: "speed",
    baseUnit: "minute per kilometer",
    tags: ["min/km", "min/mi", "s/100m"],
    keywords: ["pace", "running", "jogging", "marathon", "race", "athletics", "sports"],
    units: 4,
  },
  {
    id: "current",
    name: "Electric Current Converter",
    category: "electrical",
    baseUnit: "ampere",
    tags: ["A", "mA", "μA", "kA"],
    keywords: ["current", "electricity", "ampere", "amp", "electrical", "circuit", "wire"],
    units: 4,
  },
  {
    id: "voltage",
    name: "Voltage Converter",
    category: "electrical",
    baseUnit: "volt",
    tags: ["V", "mV", "kV", "μV"],
    keywords: ["voltage", "volt", "electricity", "electrical", "potential", "battery", "power"],
    units: 4,
  },
  {
    id: "reactive-power",
    name: "Reactive Power Converter",
    category: "electrical",
    baseUnit: "volt-ampere-reactive",
    tags: ["VAR", "kVAR", "MVAR"],
    keywords: ["reactive", "power", "electrical", "AC", "alternating", "current"],
    units: 5,
  },
  {
    id: "apparent-power",
    name: "Apparent Power Converter",
    category: "electrical",
    baseUnit: "volt-ampere",
    tags: ["VA", "kVA", "MVA"],
    keywords: ["apparent", "power", "electrical", "AC", "alternating", "current"],
    units: 5,
  },
  {
    id: "reactive-energy",
    name: "Reactive Energy Converter",
    category: "electrical",
    baseUnit: "volt-ampere-reactive hour",
    tags: ["VARh", "kVARh", "MVARh"],
    keywords: ["reactive", "energy", "electrical", "AC", "alternating", "current"],
    units: 5,
  },
  {
    id: "flow-rate",
    name: "Volume Flow Rate Converter",
    category: "flow",
    baseUnit: "cubic meter per second",
    tags: ["m³/s", "L/s", "gpm", "cfm"],
    keywords: ["flow", "rate", "volume", "liquid", "gas", "pipe", "pump", "water"],
    units: 8,
  },
  {
    id: "illuminance",
    name: "Illuminance Converter",
    category: "light",
    baseUnit: "lux",
    tags: ["lux", "fc", "phot"],
    keywords: ["light", "illuminance", "brightness", "lux", "foot-candle", "lighting"],
    units: 4,
  },
  {
    id: "frequency",
    name: "Frequency Converter",
    category: "other",
    baseUnit: "hertz",
    tags: ["Hz", "kHz", "MHz", "GHz"],
    keywords: ["frequency", "hertz", "radio", "sound", "wave", "oscillation", "vibration"],
    units: 6,
  },
  {
    id: "angle",
    name: "Angle Converter",
    category: "other",
    baseUnit: "degree",
    tags: ["°", "rad", "grad", "turn"],
    keywords: ["angle", "degree", "radian", "rotation", "circle", "geometry", "math"],
    units: 4,
  },
  {
    id: "force",
    name: "Force Converter",
    category: "mechanics",
    baseUnit: "newton",
    tags: ["N", "kN", "lbf", "kgf"],
    keywords: ["force", "newton", "pound", "push", "pull", "physics", "mechanics"],
    units: 4,
  },
  {
    id: "torque",
    name: "Torque Converter",
    category: "mechanics",
    baseUnit: "newton meter",
    tags: ["N·m", "lb·ft", "kg·cm"],
    keywords: ["torque", "twist", "rotation", "wrench", "bolt", "engine", "mechanics"],
    units: 4,
  },
  {
    id: "density",
    name: "Density Converter",
    category: "mechanics",
    baseUnit: "kilogram per cubic meter",
    tags: ["kg/m³", "g/cm³", "lb/ft³"],
    keywords: ["density", "mass", "volume", "material", "weight", "heavy", "light"],
    units: 4,
  },
  {
    id: "acceleration",
    name: "Acceleration Converter",
    category: "mechanics",
    baseUnit: "meter per second squared",
    tags: ["m/s²", "g", "ft/s²"],
    keywords: ["acceleration", "gravity", "speed", "change", "physics", "motion"],
    units: 4,
  },
  {
    id: "fuel-economy",
    name: "Fuel Economy Converter",
    category: "other",
    baseUnit: "kilometers per liter",
    tags: ["km/L", "mpg", "L/100km"],
    keywords: ["fuel", "economy", "gas", "mileage", "car", "vehicle", "efficiency"],
    units: 4,
  },
  {
    id: "data-rate",
    name: "Data Transfer Rate Converter",
    category: "digital",
    baseUnit: "bits per second",
    tags: ["bps", "Mbps", "Gbps", "KBps"],
    keywords: ["data", "transfer", "speed", "internet", "network", "bandwidth", "download"],
    units: 6,
  },
  {
    id: "resolution",
    name: "Resolution Converter",
    category: "light",
    baseUnit: "dots per inch",
    tags: ["dpi", "ppi", "lpi", "dpcm"],
    keywords: ["resolution", "print", "screen", "pixel", "dot", "image", "quality"],
    units: 4,
  },
]

// Categories for filtering
export const categories = [
  { id: "all", name: "All Categories" },
  { id: "mass", name: "Mass" },
  { id: "length", name: "Length" },
  { id: "area", name: "Area" },
  { id: "volume", name: "Volume" },
  { id: "temperature", name: "Temperature" },
  { id: "time", name: "Time" },
  { id: "speed", name: "Speed" },
  { id: "pressure", name: "Pressure" },
  { id: "energy", name: "Energy" },
  { id: "power", name: "Power" },
  { id: "digital", name: "Digital" },
  { id: "electrical", name: "Electrical" },
  { id: "mechanics", name: "Mechanics" },
  { id: "flow", name: "Flow & Rate" },
  { id: "light", name: "Light & Optics" },
  { id: "other", name: "Other" },
]