import { Ruler, Weight, Square, Droplet, Thermometer, Clock, Gauge, Zap, Power, HardDrive, Bolt, Cog, Wind, Lightbulb, MoreHorizontal, LucideIcon, Waves, Activity, ArrowUpFromLine } from "lucide-react"

export interface UnitConfig {
  value: string
  label: string
  factor: number
}

export interface ConverterConfig {
  id: string
  name: string
  category: string
  units: UnitConfig[]
  baseUnit: string
  formula?: string
  about: string
  tags?: string[]
  keywords?: string[]
}

export interface CategoryConfig {
  id: string
  name: string
  icon: LucideIcon
  color: string
  bgColor: string
  description: string
  hidden?: boolean
}

export const categories: CategoryConfig[] = [
  { id: "mass", name: "Mass", icon: Weight, color: "text-blue-500", bgColor: "bg-blue-500/10", description: "Convert weight and mass units like kg, lb, oz" },
  { id: "length", name: "Length", icon: Ruler, color: "text-green-500", bgColor: "bg-green-500/10", description: "Convert distance and length units like m, ft, mi" },
  { id: "area", name: "Area", icon: Square, color: "text-yellow-500", bgColor: "bg-yellow-500/10", description: "Convert area units like m², acre, hectare" },
  { id: "volume", name: "Volume", icon: Droplet, color: "text-cyan-500", bgColor: "bg-cyan-500/10", description: "Convert volume units like L, gal, m³" },
  { id: "temperature", name: "Temperature", icon: Thermometer, color: "text-red-500", bgColor: "bg-red-500/10", description: "Convert temperature units like °C, °F, K" },
  { id: "time", name: "Time", icon: Clock, color: "text-indigo-500", bgColor: "bg-indigo-500/10", description: "Convert time units like s, min, hr, day", hidden: true },
  { id: "speed", name: "Speed", icon: Gauge, color: "text-orange-500", bgColor: "bg-orange-500/10", description: "Convert speed units like km/h, mph, m/s" },
  { id: "pressure", name: "Pressure", icon: Gauge, color: "text-pink-500", bgColor: "bg-pink-500/10", description: "Convert pressure units like Pa, bar, psi" },
  { id: "head", name: "Pump Head", icon: Waves, color: "text-blue-600", bgColor: "bg-blue-600/10", description: "Convert pump head units like m, ft" },
  { id: "npsh", name: "NPSH", icon: ArrowUpFromLine, color: "text-cyan-600", bgColor: "bg-cyan-600/10", description: "Convert NPSH units like m, ft" },
  { id: "suction-pressure", name: "Suction Pressure", icon: Gauge, color: "text-purple-600", bgColor: "bg-purple-600/10", description: "Convert suction pressure units like Pa, bar, psi" },
  { id: "vapour-pressure", name: "Vapour Pressure", icon: Gauge, color: "text-rose-600", bgColor: "bg-rose-600/10", description: "Convert vapour pressure units like Pa, bar, psi" },
  { id: "energy", name: "Energy", icon: Zap, color: "text-amber-500", bgColor: "bg-amber-500/10", description: "Convert energy units like J, kWh, cal", hidden: true },
  { id: "power", name: "Power", icon: Power, color: "text-lime-500", bgColor: "bg-lime-500/10", description: "Convert power units like W, kW, hp" },
  { id: "digital", name: "Digital", icon: HardDrive, color: "text-teal-500", bgColor: "bg-teal-500/10", description: "Convert digital storage units like KB, MB, GB", hidden: true },
  { id: "electrical", name: "Electrical", icon: Bolt, color: "text-violet-500", bgColor: "bg-violet-500/10", description: "Convert electrical units like A, V, VAR" },
  { id: "mechanics", name: "Mechanics", icon: Cog, color: "text-slate-500", bgColor: "bg-slate-500/10", description: "Convert mechanical units like N, torque, density" },
  { id: "flow", name: "Flow & Rate", icon: Wind, color: "text-sky-500", bgColor: "bg-sky-500/10", description: "Convert flow rate units like m³/s, gpm, cfm" },
  { id: "viscosity", name: "Viscosity", icon: Activity, color: "text-purple-500", bgColor: "bg-purple-500/10", description: "Convert viscosity units like cP, cSt, Pa·s" },
  { id: "light", name: "Light & Optics", icon: Lightbulb, color: "text-yellow-400", bgColor: "bg-yellow-400/10", description: "Convert light units like lux, dpi, resolution", hidden: true },
]

export const converters: ConverterConfig[] = [
  {
    id: "mass",
    name: "Mass Converter",
    category: "mass",
    baseUnit: "gram",
    about: "Convert between different mass and weight units including metric (microgram, milligram, gram, kilogram, metric ton) and imperial (ounce, pound) systems. Perfect for cooking, shipping, science, and everyday weight measurements.",
    tags: ["mg", "g", "kg", "lb", "oz", "ton"],
    keywords: ["weight", "mass", "kilogram", "pound", "gram", "ounce", "metric", "imperial"],
    units: [
      { value: "mcg", label: "Microgram", factor: 0.000001 },
      { value: "mg", label: "Milligram", factor: 0.001 },
      { value: "g", label: "Gram", factor: 1 },
      { value: "kg", label: "Kilogram", factor: 1000 },
      { value: "lb", label: "Pound", factor: 453.592 },
      { value: "oz", label: "Ounce", factor: 28.3495 },
      { value: "ton", label: "Metric Ton", factor: 1000000 },
    ],
  },
  {
    id: "length",
    name: "Length Converter",
    category: "length",
    baseUnit: "meter",
    about: "Convert between length and distance units including millimeter, centimeter, meter, kilometer, inch, foot, yard, mile, and nautical mile. Useful for construction, travel, sports, and engineering applications.",
    units: [
      { value: "mm", label: "Millimeter", factor: 0.001 },
      { value: "cm", label: "Centimeter", factor: 0.01 },
      { value: "m", label: "Meter", factor: 1 },
      { value: "km", label: "Kilometer", factor: 1000 },
      { value: "in", label: "Inch", factor: 0.0254 },
      { value: "ft", label: "Foot", factor: 0.3048 },
      { value: "yd", label: "Yard", factor: 0.9144 },
      { value: "mi", label: "Mile", factor: 1609.344 },
      { value: "nmi", label: "Nautical Mile", factor: 1852 },
    ],
  },
  {
    id: "area",
    name: "Area Converter",
    category: "area",
    baseUnit: "square meter",
    about: "Convert between area units including square millimeter, square centimeter, square meter, square kilometer, acre, hectare, and square foot. Essential for real estate, land measurement, and property calculations.",
    units: [
      { value: "mm²", label: "Square Millimeter", factor: 0.000001 },
      { value: "cm²", label: "Square Centimeter", factor: 0.0001 },
      { value: "m²", label: "Square Meter", factor: 1 },
      { value: "km²", label: "Square Kilometer", factor: 1000000 },
      { value: "acre", label: "Acre", factor: 4046.8564224 },
      { value: "ha", label: "Hectare", factor: 10000 },
      { value: "ft²", label: "Square Foot", factor: 0.09290304 },
    ],
  },
  {
    id: "volume",
    name: "Volume Converter",
    category: "volume",
    baseUnit: "liter",
    about: "Convert between volume and capacity units including milliliter, liter, cubic meter, gallon, quart, pint, cup, and fluid ounce. Perfect for cooking, chemistry, and liquid measurements.",
    units: [
      { value: "ml", label: "Milliliter", factor: 0.001 },
      { value: "L", label: "Liter", factor: 1 },
      { value: "m³", label: "Cubic Meter", factor: 1000 },
      { value: "gal", label: "Gallon (US)", factor: 3.78541 },
      { value: "qt", label: "Quart", factor: 0.946353 },
      { value: "pt", label: "Pint", factor: 0.473176 },
      { value: "cup", label: "Cup", factor: 0.236588 },
      { value: "fl oz", label: "Fluid Ounce", factor: 0.0295735 },
    ],
  },
  {
    id: "temperature",
    name: "Temperature Converter",
    category: "temperature",
    baseUnit: "celsius",
    formula: "special",
    about: "Convert between temperature scales including Celsius (°C), Fahrenheit (°F), Kelvin (K), and Rankine (°R). Essential for weather, cooking, science, and engineering applications worldwide.",
    units: [
      { value: "C", label: "Celsius", factor: 1 },
      { value: "F", label: "Fahrenheit", factor: 1 },
      { value: "K", label: "Kelvin", factor: 1 },
      { value: "R", label: "Rankine", factor: 1 },
    ],
  },
  {
    id: "time",
    name: "Time Converter",
    category: "time",
    baseUnit: "second",
    about: "Convert between time units including millisecond, second, minute, hour, day, week, month, year, and decade. Useful for project planning, scheduling, and time calculations.",
    units: [
      { value: "ms", label: "Millisecond", factor: 0.001 },
      { value: "s", label: "Second", factor: 1 },
      { value: "min", label: "Minute", factor: 60 },
      { value: "hr", label: "Hour", factor: 3600 },
      { value: "day", label: "Day", factor: 86400 },
      { value: "week", label: "Week", factor: 604800 },
      { value: "month", label: "Month", factor: 2628000 },
      { value: "year", label: "Year (Julian)", factor: 31557600 },
      { value: "decade", label: "Decade (Julian)", factor: 315576000 },
    ],
  },
  {
    id: "digital",
    name: "Digital Storage Converter",
    category: "digital",
    baseUnit: "byte",
    about: "Convert between digital storage units including bit, byte, kilobyte (KB), megabyte (MB), gigabyte (GB), and terabyte (TB). Essential for computing, file sizes, and data storage calculations.",
    units: [
      { value: "bit", label: "Bit", factor: 0.125 },
      { value: "B", label: "Byte", factor: 1 },
      { value: "KB", label: "Kilobyte", factor: 1024 },
      { value: "MB", label: "Megabyte", factor: 1048576 },
      { value: "GB", label: "Gigabyte", factor: 1073741824 },
      { value: "TB", label: "Terabyte", factor: 1099511627776 },
    ],
  },
  {
    id: "speed",
    name: "Speed Converter",
    category: "speed",
    baseUnit: "meter per second",
    about: "Convert between speed and velocity units including meters per second (m/s), kilometers per hour (km/h), miles per hour (mph), knot, and feet per second. Perfect for vehicles, wind speed, and physics calculations.",
    units: [
      { value: "m/s", label: "Meters per Second", factor: 1 },
      { value: "km/h", label: "Kilometers per Hour", factor: 0.277778 },
      { value: "mph", label: "Miles per Hour", factor: 0.44704 },
      { value: "knot", label: "Knot", factor: 0.514444 },
      { value: "ft/s", label: "Feet per Second", factor: 0.3048 },
    ],
  },
  {
    id: "pressure",
    name: "Pressure Converter",
    category: "pressure",
    baseUnit: "pascal",
    about: "Convert between pressure units including pascal (Pa), kilopascal (kPa), megapascal (MPa), bar, millibar, PSI, atmosphere (atm), kg/cm², mmH2O, and mmHg. Essential for tire pressure, weather, engineering, and scientific applications.",
    units: [
      { value: "MPa", label: "Megapascal", factor: 1000000 },
      { value: "kPa", label: "Kilopascal", factor: 1000 },
      { value: "Pa", label: "Pascal", factor: 1 },
      { value: "bar", label: "Bar", factor: 100000 },
      { value: "mbar", label: "Millibar", factor: 100 },
      { value: "atm", label: "Atmosphere", factor: 101325 },
      { value: "kg/cm²", label: "Kilogram per Square Centimeter", factor: 98066.5 },
      { value: "mmH2O", label: "Millimeter of Water", factor: 9.80665 },
      { value: "mmHg", label: "Millimeter of Mercury", factor: 133.322 },
      { value: "psi", label: "PSI", factor: 6894.76 },
    ],
  },
  {
    id: "energy",
    name: "Energy Converter",
    category: "energy",
    baseUnit: "joule",
    about: "Convert between energy units including joule (J), kilojoule (kJ), calorie, kilocalorie, watt hour (Wh), and kilowatt hour (kWh). Useful for nutrition, electricity, and physics calculations.",
    units: [
      { value: "J", label: "Joule", factor: 1 },
      { value: "kJ", label: "Kilojoule", factor: 1000 },
      { value: "cal", label: "Calorie", factor: 4.184 },
      { value: "kcal", label: "Kilocalorie", factor: 4184 },
      { value: "Wh", label: "Watt Hour", factor: 3600 },
      { value: "kWh", label: "Kilowatt Hour", factor: 3600000 },
    ],
  },
  {
    id: "power",
    name: "Power Converter",
    category: "power",
    baseUnit: "kilowatt",
    about: "Convert between power units including watt (W), kilowatt (kW), megawatt (MW), horsepower (HP), brake horsepower (BHP), water horsepower (WHP), metric horsepower (PS), and BTU per hour. Essential for electrical systems, engines, pumps, and energy consumption calculations.",
    units: [
      { value: "W", label: "Watt", factor: 0.001 },
      { value: "kW", label: "Kilowatt", factor: 1 },
      { value: "MW", label: "Megawatt", factor: 1000 },
      { value: "hp", label: "Horsepower (Imperial)", factor: 0.7457 },
      { value: "BHP", label: "Brake Horsepower", factor: 0.7457 },
      { value: "WHP", label: "Water Horsepower (Hydraulic)", factor: 0.7457 },
      { value: "PS", label: "Pferdestärke (Metric HP)", factor: 0.7355 },
      { value: "BTU/h", label: "BTU per Hour", factor: 0.00029307 },
    ],
  },
  {
    id: "current",
    name: "Electric Current Converter",
    category: "electrical",
    baseUnit: "ampere",
    about: "Convert between electric current units including microampere (μA), milliampere (mA), ampere (A), and kiloampere (kA). Essential for electrical engineering and circuit design.",
    units: [
      { value: "μA", label: "Microampere", factor: 0.000001 },
      { value: "mA", label: "Milliampere", factor: 0.001 },
      { value: "A", label: "Ampere", factor: 1 },
      { value: "kA", label: "Kiloampere", factor: 1000 },
    ],
  },
  {
    id: "voltage",
    name: "Voltage Converter",
    category: "electrical",
    baseUnit: "volt",
    about: "Convert between voltage units including microvolt (μV), millivolt (mV), volt (V), and kilovolt (kV). Important for electrical systems, batteries, and power distribution.",
    units: [
      { value: "μV", label: "Microvolt", factor: 0.000001 },
      { value: "mV", label: "Millivolt", factor: 0.001 },
      { value: "V", label: "Volt", factor: 1 },
      { value: "kV", label: "Kilovolt", factor: 1000 },
    ],
  },
  {
    id: "reactive-power",
    name: "Reactive Power Converter",
    category: "electrical",
    baseUnit: "volt-ampere-reactive",
    about: "Convert between reactive power units including VAR, kVAR, and MVAR. Essential for AC electrical systems and power factor calculations.",
    units: [
      { value: "VAR", label: "Volt-Ampere Reactive", factor: 1 },
      { value: "kVAR", label: "Kilovolt-Ampere Reactive", factor: 1000 },
      { value: "MVAR", label: "Megavolt-Ampere Reactive", factor: 1000000 },
    ],
  },
  {
    id: "apparent-power",
    name: "Apparent Power Converter",
    category: "electrical",
    baseUnit: "volt-ampere",
    about: "Convert between apparent power units including VA, kVA, and MVA. Used in AC electrical systems for total power calculations.",
    units: [
      { value: "VA", label: "Volt-Ampere", factor: 1 },
      { value: "kVA", label: "Kilovolt-Ampere", factor: 1000 },
      { value: "MVA", label: "Megavolt-Ampere", factor: 1000000 },
    ],
  },
  {
    id: "reactive-energy",
    name: "Reactive Energy Converter",
    category: "electrical",
    baseUnit: "volt-ampere-reactive hour",
    about: "Convert between reactive energy units including VARh, kVARh, and MVARh. Important for electrical energy metering and billing.",
    units: [
      { value: "VARh", label: "Volt-Ampere Reactive Hour", factor: 1 },
      { value: "kVARh", label: "Kilovolt-Ampere Reactive Hour", factor: 1000 },
      { value: "MVARh", label: "Megavolt-Ampere Reactive Hour", factor: 1000000 },
    ],
  },
  {
    id: "flow-rate",
    name: "Volume Flow Rate Converter",
    category: "flow",
    baseUnit: "cubic meter per hour",
    about: "Convert between volume flow rate units including cubic meters per second/hour (m³/s, m³/h), liters per second/minute/hour, gallons per minute/hour (GPM, GPH), barrels per day (BPD), and cubic feet per minute (CFM). Essential for pump systems, HVAC, and fluid dynamics.",
    units: [
      { value: "m³/h", label: "Cubic Meters per Hour", factor: 1 },
      { value: "m³/s", label: "Cubic Meters per Second", factor: 3600 },
      { value: "L/s", label: "Liters per Second", factor: 3.6 },
      { value: "L/min", label: "Liters per Minute (LPM)", factor: 0.06 },
      { value: "L/h", label: "Liters per Hour", factor: 0.001 },
      { value: "gpm", label: "Gallons per Minute (US)", factor: 0.227125 },
      { value: "gph", label: "Gallons per Hour (US)", factor: 0.00378541 },
      { value: "bbl/day", label: "Barrels per Day (BPD)", factor: 0.0066245 },
      { value: "bbl/h", label: "Barrels per Hour (US)", factor: 0.158987 },
      { value: "cfm", label: "Cubic Feet per Minute", factor: 1.69901 },
    ],
  },
  {
    id: "gas-flow-rate",
    name: "Gas Flow Rate Converter",
    category: "flow",
    baseUnit: "standard cubic meter per hour",
    about: "Convert between gas flow rate units including standard cubic meters (Sm³/h), normal cubic meters (Nm³/h, Nm³/min), and standard cubic feet (SCFH, SCFM, MMSCFD). Essential for gas systems, industrial processes, and HVAC applications. Note: Standard conditions are 15°C and 1.01325 bar.",
    units: [
      { value: "Sm³/h", label: "Standard Cubic Meters per Hour", factor: 1 },
      { value: "Nm³/h", label: "Normal Cubic Meters per Hour", factor: 1.0549 },
      { value: "Nm³/min", label: "Normal Cubic Meters per Minute", factor: 63.294 },
      { value: "SCFH", label: "Standard Cubic Feet per Hour", factor: 35.3147 },
      { value: "SCFM", label: "Standard Cubic Feet per Minute", factor: 2118.88 },
      { value: "MMSCFD", label: "Million Standard Cubic Feet per Day", factor: 1179.87 },
    ],
  },
  {
    id: "mass-flow-rate",
    name: "Mass Flow Rate Converter",
    category: "flow",
    baseUnit: "kilogram per hour",
    about: "Convert between mass flow rate units including kilograms per hour/second (kg/h, kg/s), grams per second (g/s), pounds per hour (lb/h), and metric tons per hour (ton/h). Essential for process engineering, pump calculations, and material handling. Note: To convert between mass and volumetric flow rates, you need to know the fluid density.",
    units: [
      { value: "kg/h", label: "Kilograms per Hour", factor: 1 },
      { value: "kg/s", label: "Kilograms per Second", factor: 3600 },
      { value: "g/s", label: "Grams per Second", factor: 3.6 },
      { value: "g/h", label: "Grams per Hour", factor: 0.001 },
      { value: "lb/h", label: "Pounds per Hour", factor: 0.453592 },
      { value: "lb/s", label: "Pounds per Second", factor: 1632.93 },
      { value: "ton/h", label: "Metric Tons per Hour", factor: 1000 },
      { value: "ton/day", label: "Metric Tons per Day", factor: 41.6667 },
    ],
  },
  {
    id: "illuminance",
    name: "Illuminance Converter",
    category: "light",
    baseUnit: "lux",
    about: "Convert between illuminance units including lux, foot-candle (fc), and phot. Used in lighting design, photography, and architectural applications.",
    units: [
      { value: "lux", label: "Lux", factor: 1 },
      { value: "fc", label: "Foot-candle", factor: 10.764 },
      { value: "phot", label: "Phot", factor: 10000 },
    ],
  },
  {
    id: "force",
    name: "Force Converter",
    category: "mechanics",
    baseUnit: "newton",
    about: "Convert between force units including newton (N), kilonewton (kN), pound-force (lbf), and kilogram-force (kgf). Essential for physics, engineering, and mechanical calculations.",
    units: [
      { value: "N", label: "Newton", factor: 1 },
      { value: "kN", label: "Kilonewton", factor: 1000 },
      { value: "lbf", label: "Pound-force", factor: 4.44822 },
      { value: "kgf", label: "Kilogram-force", factor: 9.80665 },
    ],
  },
  {
    id: "torque",
    name: "Torque Converter",
    category: "mechanics",
    baseUnit: "newton meter",
    about: "Convert between torque units including newton meter (N·m), pound-foot (lb·ft), kilogram centimeter (kg·cm), and ounce-inch. Important for automotive, machinery, and mechanical engineering.",
    units: [
      { value: "N·m", label: "Newton Meter", factor: 1 },
      { value: "lb·ft", label: "Pound-foot", factor: 1.35582 },
      { value: "kg·cm", label: "Kilogram Centimeter", factor: 0.0980665 },
      { value: "oz·in", label: "Ounce-inch", factor: 0.00706155 },
    ],
  },
  {
    id: "density",
    name: "Density Converter",
    category: "mechanics",
    baseUnit: "kilogram per cubic meter",
    formula: "special",
    about: "Convert between density units including kg/m³, g/cm³, g/L, g/ml, lb/ft³, lb/gal, specific gravity (SG), and API gravity. Used in material science, engineering, oil & gas industry, and physics for mass-to-volume relationships.",
    units: [
      { value: "kg/m³", label: "Kilogram per Cubic Meter", factor: 1 },
      { value: "g/cm³", label: "Gram per Cubic Centimeter", factor: 1000 },
      { value: "g/ml", label: "Gram per Milliliter", factor: 1000 },
      { value: "g/L", label: "Gram per Liter", factor: 1 },
      { value: "lb/ft³", label: "Pound per Cubic Foot", factor: 16.0185 },
      { value: "lb/gal US", label: "Pound per US Gallon", factor: 119.8264 },
      { value: "lb/gal UK", label: "Pound per UK Gallon", factor: 99.7764 },
      { value: "SG", label: "Specific Gravity", factor: 1000 },
      { value: "°API", label: "API Gravity", factor: 1 },
    ],
  },
  {
    id: "acceleration",
    name: "Acceleration Converter",
    category: "mechanics",
    baseUnit: "meter per second squared",
    about: "Convert between acceleration units including m/s², standard gravity (g), ft/s², and gal. Essential for physics, automotive, and aerospace applications.",
    units: [
      { value: "m/s²", label: "Meter per Second Squared", factor: 1 },
      { value: "g", label: "Standard Gravity", factor: 9.80665 },
      { value: "ft/s²", label: "Foot per Second Squared", factor: 0.3048 },
      { value: "gal", label: "Gal", factor: 0.01 },
    ],
  },
  {
    id: "data-rate",
    name: "Data Transfer Rate Converter",
    category: "digital",
    baseUnit: "bits per second",
    about: "Convert between data transfer rate units including bps, kbps, Mbps, Gbps, and bytes per second. Essential for internet speed, network bandwidth, and download calculations.",
    units: [
      { value: "bps", label: "Bits per Second", factor: 1 },
      { value: "kbps", label: "Kilobits per Second", factor: 1000 },
      { value: "Mbps", label: "Megabits per Second", factor: 1000000 },
      { value: "Gbps", label: "Gigabits per Second", factor: 1000000000 },
      { value: "Bps", label: "Bytes per Second", factor: 8 },
      { value: "KBps", label: "Kilobytes per Second", factor: 8000 },
    ],
  },
  {
    id: "resolution",
    name: "Resolution Converter",
    category: "light",
    baseUnit: "dots per inch",
    about: "Convert between resolution units including DPI (dots per inch), PPI (pixels per inch), LPI (lines per inch), and dots per centimeter. Used in printing, displays, and image quality.",
    units: [
      { value: "dpi", label: "Dots per Inch", factor: 1 },
      { value: "ppi", label: "Pixels per Inch", factor: 1 },
      { value: "lpi", label: "Lines per Inch", factor: 1 },
      { value: "dpcm", label: "Dots per Centimeter", factor: 0.393701 },
    ],
  },
  {
    id: "head",
    name: "Pump Head Converter",
    category: "head",
    baseUnit: "meter",
    about: "Convert between pump head units including meters (m), feet (ft), and water column measurements. Head represents the energy per unit weight of fluid in centrifugal pumps. Essential for pump selection, performance curves, and hydraulic calculations.",
    units: [
      { value: "m", label: "Meters", factor: 1 },
      { value: "ft", label: "Feet", factor: 0.3048 },
      { value: "m H2O", label: "Meters of Water Column", factor: 1 },
      { value: "ft H2O", label: "Feet of Water Column", factor: 0.3048 },
    ],
  },
  {
    id: "npsh",
    name: "NPSH Converter",
    category: "npsh",
    baseUnit: "meter",
    about: "Convert between Net Positive Suction Head (NPSH) units including meters (m), feet (ft), and water column measurements. NPSH is critical for preventing cavitation in centrifugal pumps. Essential for pump installation and suction system design.",
    units: [
      { value: "m", label: "Meters", factor: 1 },
      { value: "ft", label: "Feet", factor: 0.3048 },
      { value: "m H2O", label: "Meters of Water Column", factor: 1 },
      { value: "ft H2O", label: "Feet of Water Column", factor: 0.3048 },
    ],
  },
  {
    id: "suction-pressure",
    name: "Suction Pressure Converter",
    category: "suction-pressure",
    baseUnit: "pascal",
    about: "Convert between suction pressure units including pascal (Pa), kilopascal (kPa), megapascal (MPa), bar, millibar, PSI, atmosphere (atm), kg/cm², mmH2O, and mmHg. Essential for pump suction systems, cavitation analysis, and hydraulic calculations.",
    units: [
      { value: "MPa", label: "Megapascal", factor: 1000000 },
      { value: "kPa", label: "Kilopascal", factor: 1000 },
      { value: "Pa", label: "Pascal", factor: 1 },
      { value: "bar", label: "Bar", factor: 100000 },
      { value: "mbar", label: "Millibar", factor: 100 },
      { value: "atm", label: "Atmosphere", factor: 101325 },
      { value: "kg/cm²", label: "Kilogram per Square Centimeter", factor: 98066.5 },
      { value: "mmH2O", label: "Millimeter of Water", factor: 9.80665 },
      { value: "mmHg", label: "Millimeter of Mercury", factor: 133.322 },
      { value: "psi", label: "PSI", factor: 6894.76 },
    ],
  },
  {
    id: "vapour-pressure",
    name: "Vapour Pressure Converter",
    category: "vapour-pressure",
    baseUnit: "pascal",
    about: "Convert between vapour pressure units including pascal (Pa), kilopascal (kPa), megapascal (MPa), bar, millibar, PSI, atmosphere (atm), kg/cm², mmH2O, and mmHg. Vapour pressure is the pressure exerted by a vapor in equilibrium with its liquid or solid phase. Essential for NPSH calculations, cavitation prevention, and thermodynamic analysis.",
    units: [
      { value: "MPa", label: "Megapascal", factor: 1000000 },
      { value: "kPa", label: "Kilopascal", factor: 1000 },
      { value: "Pa", label: "Pascal", factor: 1 },
      { value: "bar", label: "Bar", factor: 100000 },
      { value: "mbar", label: "Millibar", factor: 100 },
      { value: "atm", label: "Atmosphere", factor: 101325 },
      { value: "kg/cm²", label: "Kilogram per Square Centimeter", factor: 98066.5 },
      { value: "mmH2O", label: "Millimeter of Water", factor: 9.80665 },
      { value: "mmHg", label: "Millimeter of Mercury", factor: 133.322 },
      { value: "psi", label: "PSI", factor: 6894.76 },
    ],
  },
  {
    id: "dynamic-viscosity",
    name: "Dynamic Viscosity Converter",
    category: "viscosity",
    baseUnit: "pascal second",
    about: "Convert between dynamic (absolute) viscosity units including Pascal-second (Pa·s), milliPascal-second (mPa·s), centipoise (cP), poise (P), and decipoise (dP). Dynamic viscosity measures a fluid's resistance to flow. Essential for fluid dynamics, pump selection, and process engineering.",
    units: [
      { value: "Pa·s", label: "Pascal-second", factor: 1 },
      { value: "mPa·s", label: "MilliPascal-second", factor: 0.001 },
      { value: "cP", label: "Centipoise", factor: 0.001 },
      { value: "P", label: "Poise", factor: 0.1 },
      { value: "dP", label: "Decipoise", factor: 0.01 },
    ],
  },
  {
    id: "kinematic-viscosity",
    name: "Kinematic Viscosity Converter",
    category: "viscosity",
    baseUnit: "square millimeter per second",
    about: "Convert between kinematic viscosity units including centistokes (cSt), square millimeters per second (mm²/s), stokes (St), and square meters per second (m²/s). Kinematic viscosity is the ratio of dynamic viscosity to density. Essential for fluid flow calculations and lubricant specifications. Note: 1 cSt = 1 mm²/s.",
    units: [
      { value: "cSt", label: "Centistokes", factor: 1 },
      { value: "mm²/s", label: "Square Millimeters per Second", factor: 1 },
      { value: "St", label: "Stokes", factor: 100 },
      { value: "m²/s", label: "Square Meters per Second", factor: 1000000 },
    ],
  },
]
